version: '3.1'

services:
    php:
        build: .
        links: 
            - mysql

        volumes:
            - ./ezXSS:/var/www/html/ezXSS
        ports: 
            - "8181:9000"
    mysql:
        image: mysql:5.7
        restart: always
        volumes: 
            - ./db:/var/lib/mysql

        environment:
                 MYSQL_ROOT_PASSWORD: ezxss
                 MYSQL_DATABASE: ezxss
                 MYSQL_USER: ezxss
                 MYSQL_PASSWORD: ezxss
        ports:
            - "3306:3306"
